# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.define :vm1 do |vm1|
    vm1.vm.network :private_network, :ip => "192.168.56.10"
    vm1.vm.provision "shell", inline: <<-SHELL
      wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh 
      sh /tmp/netdata-kickstart.sh
      cd /usr/lib/netdata/conf.d/health.d
      sudo sed -i 's+(75) : (85))+(80) : (90))+g' cpu.conf
      sudo netdatacli reload-health
      cd /
      cd usr/lib/netdata/conf.d
      sudo sed -i 's+DEFAULT_RECIPIENT_EMAIL="root"+DEFAULT_RECIPIENT_EMAIL="montjpedro@gmail.com"+g' health_alarm_notify.conf
      sudo netdatacli reload-health
      sudo apt install -y sendmail
      cd /
      sudo apt-get update
      sudo apt-get install -y autoconf gcc libc6 make wget unzip apache2 php libapache2-mod-php7.2 libgd-dev
      cd /tmp
      wget -O nagioscore.tar.gz https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      tar xzf nagioscore.tar.gz
      cd /tmp/nagioscore-nagios-4.4.6/
      sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      sudo make all
      sudo make install-groups-users
      sudo usermod -a -G nagios www-data
      sudo make install
      sudo make install-daemoninit
      sudo make install-commandmode
      sudo make install-config
      sudo make install-webconf
      sudo a2enmod rewrite
      sudo a2enmod cgi
      sudo ufw allow Apache
      sudo ufw reload
      sudo htpasswd -bc /usr/local/nagios/etc/htpasswd.users nagiosadmin 123
      sudo systemctl restart apache2.service
      sudo systemctl start nagios.service
      sudo apt-get install -y nagios-plugins
      sudo ln -s /usr/lib/nagios/plugins/check_* /usr/local/nagios/libexec/
      sudo systemctl restart apache2.service
      sudo systemctl restart nagios.service
    SHELL
  end

  config.vm.define :vm2 do |vm2|
    vm2.vm.network :private_network, :ip => "192.168.56.11"
    vm2.vm.provision "shell", inline: <<-SHELL
      wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh 
      sh /tmp/netdata-kickstart.sh
      cd /usr/lib/netdata/conf.d/health.d
      sudo sed -i 's+(75) : (85))+(80) : (90))+g' cpu.conf
      sudo netdatacli reload-health
      cd /
      cd usr/lib/netdata/conf.d
      sudo sed -i 's+DEFAULT_RECIPIENT_EMAIL="root"+DEFAULT_RECIPIENT_EMAIL="montjpedro@gmail.com"+g' health_alarm_notify.conf
      sudo netdatacli reload-health
      sudo apt install -y sendmail
      cd /
      sudo apt-get update
      sudo apt-get install -y autoconf gcc libc6 make wget unzip apache2 php libapache2-mod-php7.2 libgd-dev
      cd /tmp
      wget -O nagioscore.tar.gz https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      tar xzf nagioscore.tar.gz
      cd /tmp/nagioscore-nagios-4.4.6/
      sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      sudo make all
      sudo make install-groups-users
      sudo usermod -a -G nagios www-data
      sudo make install
      sudo make install-daemoninit
      sudo make install-commandmode
      sudo make install-config
      sudo make install-webconf
      sudo a2enmod rewrite
      sudo a2enmod cgi
      sudo ufw allow Apache
      sudo ufw reload
      sudo htpasswd -bc /usr/local/nagios/etc/htpasswd.users nagiosadmin 123
      sudo systemctl restart apache2.service
      sudo systemctl start nagios.service
      sudo apt-get install -y nagios-plugins
      sudo ln -s /usr/lib/nagios/plugins/check_* /usr/local/nagios/libexec/
      sudo systemctl restart apache2.service
      sudo systemctl restart nagios.service
    SHELL
  end

  config.vm.define :vm3 do |vm3|
    vm3.vm.network :private_network, :ip => "192.168.56.13"
    vm3.vm.provision "shell", inline: <<-SHELL
      wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh 
      sh /tmp/netdata-kickstart.sh
      cd /usr/lib/netdata/conf.d/health.d
      sudo sed -i 's+(75) : (85))+(80) : (90))+g' cpu.conf
      sudo netdatacli reload-health
      cd /
      cd usr/lib/netdata/conf.d
      sudo sed -i 's+DEFAULT_RECIPIENT_EMAIL="root"+DEFAULT_RECIPIENT_EMAIL="montjpedro@gmail.com"+g' health_alarm_notify.conf
      sudo netdatacli reload-health
      sudo apt install -y sendmail
      cd /
      sudo apt-get update
      sudo apt-get install -y autoconf gcc libc6 make wget unzip apache2 php libapache2-mod-php7.2 libgd-dev
      cd /tmp
      wget -O nagioscore.tar.gz https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      tar xzf nagioscore.tar.gz
      cd /tmp/nagioscore-nagios-4.4.6/
      sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      sudo make all
      sudo make install-groups-users
      sudo usermod -a -G nagios www-data
      sudo make install
      sudo make install-daemoninit
      sudo make install-commandmode
      sudo make install-config
      sudo make install-webconf
      sudo a2enmod rewrite
      sudo a2enmod cgi
      sudo ufw allow Apache
      sudo ufw reload
      sudo htpasswd -bc /usr/local/nagios/etc/htpasswd.users nagiosadmin 123
      sudo systemctl restart apache2.service
      sudo systemctl start nagios.service
      sudo apt-get install -y nagios-plugins
      sudo ln -s /usr/lib/nagios/plugins/check_* /usr/local/nagios/libexec/
      sudo systemctl restart apache2.service
      sudo systemctl restart nagios.service
    SHELL
  end

  config.vm.define :ansible do |ansible|
    ansible.vm.network :private_network, :ip => "192.168.56.12"
    ansible.vm.synced_folder "./data", "/vagrant_data"
    ansible.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt install -y software-properties-common
      add-apt-repository --yes --update ppa:ansible/ansible
      apt install -y ansible
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end
  
  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
